name: Build Eclipse

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
            build-type: RelWithDebInfo
          - name: macOS
            os: macos-latest
          - name: Android32
            os: ubuntu-latest
            target: Android32
          - name: Android64
            os: ubuntu-latest
            target: Android64

    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build the mod
        uses: geode-sdk/build-geode-mod@main
        with:
          sdk: nightly
          combine: true
          export-pdb: true
          target: ${{ matrix.config.target }}
          build-config: ${{ matrix.config.build-type || 'Release' }}

  package:
    name: Package builds
    runs-on: ubuntu-latest
    needs: ['build']

    steps:
      - name: Combine build artifacts
        uses: geode-sdk/build-geode-mod/combine@main
        id: build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build Output
          path: ${{ steps.build.outputs.build-output }}

      - name: Check if nightly webhook is set
        id: check
        if: github.ref == 'refs/heads/main'
        run: echo "has-nightly-webhook=${{ secrets.NIGHTLY_WEBHOOK != '' }}" >> $GITHUB_OUTPUT

      - name: Checkout repository
        if: ${{ steps.check.outputs.has-nightly-webhook == 'true' }}
        uses: actions/checkout@v4

      - name: Get commit messages
        id: commit
        if: ${{ steps.check.outputs.has-nightly-webhook == 'true' }}
        run: |
          echo "commit-message=$(git log -1 --pretty=format:'%s' | head -n 1)" >> $GITHUB_OUTPUT
          echo "build-color=#$(git log -1 --pretty=format:'%h' | cut -c 1-6)" >> $GITHUB_OUTPUT

      - name: Upload release to Discord
        uses: Prevter/discord-webhook@main
        if: ${{ steps.check.outputs.has-nightly-webhook == 'true' }}
        with:
          webhook-url: ${{ secrets.NIGHTLY_WEBHOOK }}
          content: 'New nightly build available!'
          files: ${{ steps.build.outputs.build-output }}/*.geode
          embed-title: ${{ steps.commit.outputs.commit-message }}
          embed-color: ${{ steps.commit.outputs.build-color }}
          embed-url: ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
          embed-author: ${{ github.actor }}
          embed-author-icon: 'https://avatars.githubusercontent.com/u/${{ github.actor_id }}?v=4'
          embed-timestamp: 'now'
          debug-print: true
